module.exports = {
  DEFAULT_API_URL: 'https://api.e3db.com',
  DEFAULT_QUERY_COUNT: 100,
  IDENTITY_DERIVATION_ROUNDS: 10000,
  EMAIL: /(.+)@(.+){2,}\.(.+){2,}/,
  DEFAULT_KDF_ITERATIONS: 1000,
  FILE_VERSION: 3,
  FILE_BLOCK_SIZE: 65536,
  TSV1_SUPPORTED_ALGORITHMS: ['TSV1-ED25519-BLAKE2B'],
}
